[theme]
primaryColor = "#F5821E"
backgroundColor = "#F7F8F9"
secondaryBackgroundColor = "#ECEFF1"
textColor = "#151C21"
font = "sans serif"

[server]
headless = true
maxUploadSize = 50

[browser]
gatherUsageStats = false
